= Project Road Scholar

_Streamline Course Lifecycle_

== Project Objective

This project will develop/organize a set of processes, tools, and resources to make the course lifecycle in GPTE more robust and predictable. This is critical for satisfying the growing demand for GPTE courses.

== Project Scope

This project covers internal GPTE processes and tools, including: course development and release processes, integration with the LMSes (internal and partner), Train-the-Trainer programs.

== Project Components

=== Simplify and Standardize Course Development

* Course structure, template, author's guide
* Course deployment framework (homeroom/Jupyter)
* Course QA process


=== Fine-tune Course Release Process
* Roadmap based on the feedback from stakeholders
* Scheduled, predictable releases 
* Measurable/planned effort
* Course lifecycle support: plan, develop, pilot, release, update, support, retire


=== Integrate with LMS
* Course < - > Learning Path; cross-pollination 
* Competency Models < - > Accreditation Profiles
* Automate (some) tasks (e.g. datasheet)





== Useful resources

Semantic versioning: https://semver.org/

Keep a Changelog: https://keepachangelog.com/en/1.0.0/

Trunk-based development: https://trunkbaseddevelopment.com/

Minor Course Updates (by Randy) https://docs.google.com/document/d/1VcxYiAeX7-Ytfl-Hun-sbGWzNHo7EtjAgEr_A3s8aH8/edit#heading=h.dmitvv1qolkk

GPTE - Content/Program Review & Lifecycle (by Dana Lorichon) https://docs.google.com/document/d/1TxN2UsUVj2-6fxdzcv2VJJOuhDImywREgIMHric-IiU/edit

Process from Upstream Lab to Production ILT/ELT Module (Sha & WK): https://docs.google.com/document/d/1K95e9YzN-8A2rRAHha_lixRts35qfdJoxQb3j-lKK2E/edit#heading=h.64lxad8zqe8w

Asciidoc toolchain used by GLS: https://mojo.redhat.com/docs/DOC-1207111

Git Flow vs Trunk-based development: https://www.toptal.com/software/trunk-based-development-git-flow (short and clean overview with pros and cons)

Red Hat's Asciidoc markup conventions: https://redhat-documentation.github.io/asciidoc-markup-conventions/


== Course Development

=== Sources
* Competency Model
* Accreditation Profiles
* Consulting, SA, BU feedback
* Product roadmap
* Team priorities

=== Process
* Skills subset (what you are going to learn here)
* Part of which Learning Path and/or Accreditation Profile is it going to be?
* Upstream lab(s) (aka "blog")
* Lab environment (agnosticV)


